In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# PHASE 1 — IMPORT AND EXPLORE THE DATA

In [ ]:
df = pd.read_csv('/content/signal-data.csv')
print(df.head())

                  Time        0        1          2          3       4      5  \
0  2008-07-19 11:55:00  3030.93  2564.00  2187.7333  1411.1265  1.3602  100.0
1  2008-07-19 12:32:00  3095.78  2465.14  2230.4222  1463.6606  0.8294  100.0
2  2008-07-19 13:17:00  2932.61  2559.94  2186.4111  1698.0172  1.5102  100.0
3  2008-07-19 14:43:00  2988.72  2479.90  2199.0333   909.7926  1.3204  100.0
4  2008-07-19 15:22:00  3032.24  2502.87  2233.3667  1326.5200  1.5334  100.0

          6       7       8  ...       581     582     583     584      585  \
0   97.6133  0.1242  1.5005  ...       NaN  0.5005  0.0118  0.0035   2.3630
1  102.3433  0.1247  1.4966  ...  208.2045  0.5019  0.0223  0.0055   4.4447
2   95.4878  0.1241  1.4436  ...   82.8602  0.4958  0.0157  0.0039   3.1745
3  104.2367  0.1217  1.4882  ...   73.8432  0.4990  0.0103  0.0025   2.0544
4  100.3967  0.1235  1.5031  ...       NaN  0.4800  0.4766  0.1045  99.3032

      586     587     588       589  Pass/Fail
0     NaN     NaN     NaN       NaN       -1.0
1  0.0096  0.0201  0.0060  208.2045       -1.0
2  0.0584  0.0484  0.0148   82.8602        1.0
3  0.0202  0.0149  0.0044   73.8432       -1.0
4  0.0202  0.0149  0.0044   73.8432       -1.0

[5 rows x 592 columns]

In [ ]:
df.shape

(1361, 592)

In [ ]:
print("Displaying first 5 rows:")
print(df.head(5))

print("Displaying last 5 rows:")
print(df.tail(5))

Displaying first 5 rows:
                  Time        0        1          2          3       4      5  \
0  2008-07-19 11:55:00  3030.93  2564.00  2187.7333  1411.1265  1.3602  100.0
1  2008-07-19 12:32:00  3095.78  2465.14  2230.4222  1463.6606  0.8294  100.0
2  2008-07-19 13:17:00  2932.61  2559.94  2186.4111  1698.0172  1.5102  100.0
3  2008-07-19 14:43:00  2988.72  2479.90  2199.0333   909.7926  1.3204  100.0
4  2008-07-19 15:22:00  3032.24  2502.87  2233.3667  1326.5200  1.5334  100.0

          6       7       8  ...       581     582     583     584      585  \
0   97.6133  0.1242  1.5005  ...       NaN  0.5005  0.0118  0.0035   2.3630
1  102.3433  0.1247  1.4966  ...  208.2045  0.5019  0.0223  0.0055   4.4447
2   95.4878  0.1241  1.4436  ...   82.8602  0.4958  0.0157  0.0039   3.1745
3  104.2367  0.1217  1.4882  ...   73.8432  0.4990  0.0103  0.0025   2.0544
4  100.3967  0.1235  1.5031  ...       NaN  0.4800  0.4766  0.1045  99.3032

      586     587     588       589  Pass/Fail
0     NaN     NaN     NaN       NaN       -1.0
1  0.0096  0.0201  0.0060  208.2045       -1.0
2  0.0584  0.0484  0.0148   82.8602        1.0
3  0.0202  0.0149  0.0044   73.8432       -1.0
4  0.0202  0.0149  0.0044   73.8432       -1.0

[5 rows x 592 columns]
Displaying last 5 rows:
                     Time        0        1          2          3       4  \
1356  2008-09-25 15:12:00  3016.34  2538.44  2266.8333  2040.1937  1.6558
1357  2008-09-25 15:40:00  2978.96      NaN  2250.3667  1847.0925  2.0218
1358  2008-09-25 15:55:00  2911.84  2507.04  2176.4667  1024.0477  1.2782
1359  2008-09-25 16:44:00  2888.58  2481.37  2200.2000  1121.1875  1.3171
1360  2008-09-25 17:28:00  3043.77  2588.52  2219.7667  2086.4710  1.3381

          5         6       7       8  ...      581     582     583     584  \
1356  100.0   94.8489  0.1216  1.3613  ...  89.9060  0.5022  0.0132  0.0033
1357  100.0   91.0589  0.1214  1.3809  ...  44.2355  0.5045  0.0115  0.0033
1358  100.0  105.7178  0.1203  1.3573  ...      NaN  0.4999  0.0088  0.0024
1359  100.0  103.8978  0.1191  1.4342  ...      NaN  0.4980  0.0209  0.0044
1360  100.0   98.8900  0.1234  1.4575  ...      NaN     NaN     NaN     NaN

         585     586     587     588      589  Pass/Fail
1356  2.6243  0.0206  0.0185  0.0056  89.9060       -1.0
1357  2.2871  0.0389  0.0172  0.0052  44.2355       -1.0
1358  1.7623  0.0389  0.0172  0.0052  44.2355       -1.0
1359  4.1921  0.0389  0.0172  0.0052  44.2355       -1.0
1360     NaN     NaN     NaN     NaN      NaN        NaN

[5 rows x 592 columns]

In [ ]:
df.columns

Index(['Time', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       ...
       '581', '582', '583', '584', '585', '586', '587', '588', '589',
       'Pass/Fail'],
      dtype='object', length=592)

In [ ]:
df.dtypes

Time          object
0            float64
1            float64
2            float64
3            float64
              ...
586          float64
587          float64
588          float64
589          float64
Pass/Fail    float64
Length: 592, dtype: object

In [ ]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,581,582,583,584,585,586,587,588,589,Pass/Fail
count,1354.000000,1355.000000,1355.000000,1355.000000,1355.000000,1355.0,1355.000000,1355.000000,1361.000000,1361.000000,...,484.000000,1357.000000,1357.000000,1357.000000,1357.000000,1358.000000,1358.000000,1358.000000,1358.000000,1359.000000
mean,3011.955458,2493.923771,2198.963013,1366.423207,1.287780,100.0,101.650859,0.122345,1.475092,-0.001039,...,95.737736,0.500152,0.015468,0.003901,3.098120,0.020554,0.016485,0.005286,102.473218,-0.852833
std,66.270580,86.394381,29.394139,343.446824,0.376463,0.0,4.428063,0.001909,0.068022,0.014924,...,85.959099,0.003561,0.018378,0.003985,3.828921,0.011453,0.008292,0.002605,98.005068,0.522376
min,2743.240000,2158.750000,2060.660000,847.797600,0.681500,100.0,83.423300,0.116000,1.191000,-0.053400,...,0.000000,0.477800,0.006500,0.001700,1.284500,-0.004200,0.004200,0.001500,0.000000,-1.000000
25%,2967.130000,2449.255000,2180.700000,1084.377900,0.979000,100.0,99.250000,0.121000,1.429300,-0.010800,...,46.339300,0.498000,0.011500,0.003100,2.299800,0.012225,0.010600,0.003400,45.258200,-1.000000
50%,3010.560000,2497.450000,2199.333400,1302.660700,1.310100,100.0,101.973300,0.122200,1.472600,-0.000900,...,72.200200,0.500200,0.013800,0.003600,2.768100,0.020000,0.014900,0.004600,73.395650,-1.000000
75%,3056.467500,2538.240000,2217.961100,1588.509000,1.512650,100.0,104.530000,0.123700,1.527000,0.008800,...,113.578250,0.502500,0.016600,0.004100,3.315400,0.027675,0.021000,0.006675,119.989900,-1.000000
max,3266.040000,2846.440000,2315.266700,3715.041700,3.889400,100.0,111.890000,0.128600,1.656400,0.046800,...,706.824000,0.509800,0.476600,0.104500,99.303200,0.058400,0.060700,0.018800,706.824000,1.000000

In [ ]:
df.isnull().sum()

Time         0
0            7
1            6
2            6
3            6
            ..
586          3
587          3
588          3
589          3
Pass/Fail    2
Length: 592, dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(40710)

In [ ]:
df.duplicated().sum()

np.int64(272)

In [ ]:
df['Pass/Fail'].value_counts()

Pass/Fail
-1.0    1259
 1.0     100
Name: count, dtype: int64

In [ ]:
df['Pass/Fail'].value_counts(normalize=True)*100

Pass/Fail
-1.0    92.641648
 1.0     7.358352
Name: proportion, dtype: float64